### PR TITLE
Removed warning about firmware spoofing

### PR DESCRIPTION
**Pull request by mariogamer2**
Since d02f868595f32884cce3d8569707afba06de847d ,downgrade and update work with firmware spoofing,a friend on a forum tested

### CODE REVIEW

**Comment by Mrrraou** [comment]
I wouldn't take that risk, seriously. It would be better to keep it.

**Comment by profi200** [comment]
I have looked into the source and AM_InstallNativeFirm() was replaced by AM_InstallFirm(). Theoretically it should not brick anymore at least because of this but i can't guarantee anything still.

**Comment by Mrrraou** [comment]
It could, if using for example FIRM partition writing patches (like CakesFW
has for example).

**Comment by mariogamer2** [comment]
@profi200 I can get more people to test,also,do not merge or close,please.

**Pull request closed without merging**
