### PR TITLE
Improve stability.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Substance12** [comment]
Wait, so it is confirmed to work? It hasn't even been an hour since you forked it

**Comment by Steveice10** [comment]
@Substance12 Code looks good to me, and I've been told that the actual downgrade process itself didn't have any errors, which is what I was mainly looking for. Testing is still in progress, but I decided to go ahead and set up the pull request.

**Comment by Substance12** [comment]
Okay. So, just to make sure, will TuxSH or you make a new thread on GBATemp when the code reaches a good state?

**Comment by Steveice10** [comment]
No idea. I'm just looking to improve the stability of the master branch at the moment, not produce release builds.

**Comment by Substance12** [comment]
Wish you the best of lucks.

**Comment by dark-samus** [comment]
seems to be confirmed that this helps...

using Steveice10's version it was attempted to interrupt the downgrade in the middle of it (the user had a hardmod) here are the results:

ok, downgrading from 9.8....

waited for about 10 titles installed (right when the app title started to scroll), shut it off
it booted
shows 9.2.0-20U on mset
booting 9.8 cubic ninja resulted in black error screen
booting 9.2 cubic ninja worked.
that's where i'm at now

Gonna see if i can finish the downgrade, if not, try to update to 10.3

then:

ok, i was able to launch sysupdater again and finish the downgrade.

**Comment by Steveice10** [comment]
Revised to use a cleaner sorting system.

**Pull request merged**
