### PR TITLE
Sort safe mode titles ahead of others.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Substance12** [comment]
Nice... you guys are making great progress in such a shot span of time.

**Comment by Substance12** [comment]
Technically, this would help us recover from pretty much any soft brick? Also, have you guys looked into the "Rebooting in 10 seconds..." bug?

**Comment by Steveice10** [comment]
@Substance12 I have noticed that it sometimes hangs at rebooting, however that *could* be due to memchunkhax2 stability issues when exiting? Either way, it hanging there shouldn't cause any issues itself, as it just calls APT_HardwareResetAsync.

**Comment by Substance12** [comment]
I've seen a lot of reports of people who shut down their 3DSs after staring at the reboot screen for a long time and they got a brick.

**Comment by Steveice10** [comment]
@Substance12 Then it's likely an unrelated issue during the install process.

**Comment by Substance12** [comment]
Alright. But this commit alone will help a ton.

**Pull request merged**
